## eigen value /  eigen vector!
행렬 A를 선형변환으로 봤을 때, 선형변환 A에 의한 변환 결과가 자기 자신의 상수배가 되는
0이 아닌 vector를 eigenvector라고 한다. 이때 상수배는 eigenvalue이다.

![notation](https://t1.daumcdn.net/cfile/tistory/237AB44F525CD4BC08)

- eigenvalue - eigenvector는 아예 존재하지 않을 수도 있다.
- 최대 n개까지 존재할 수 있다.



## How to get eigen value /  eigen vector!

$$
Ax = \lambda x
$$

$A$ 는 maxtrix, $x$는 eigen vector $\lambda$는 eigen value를 나타낸다.

위의 식을 조금 변형시키면,아래와 같이 전개된다.

$$
(A - \lambda {I})x = 0
$$

이를 해석하면 새로운 matrix$(A - \lambda {I})$의 선형변환에 의해서 $x$는 zero vector가 되어야한다.
(단, x는 zero vector가 아니다.)

여기서 기하학적인 의미를 더 고민해보고 싶다면 [Eigenvectors and eigenvalues](https://www.youtube.com/watch?v=PFDu9oVAE-g&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=14)를 참고하시면 좋을 것 같습니다.

## Diagonalization
![](https://www.mathdoubts.com/imgs/matrix/principal-diagonal.png)
대각화는 square matrix $A \in R^{n \times n}$ 을 아래와 같은 형식으로 변형하는 것이다.

$
D = V^{-1}AV  
$
where $V$ is invertable matrix

항상 대각화가 가능한 것은 아니다, invertable $V$가 존재할 때 $D = V^{-1}AV$ 가diagonal matrix가 될 수 있다.

대각행렬은 아래와 같은 과정을 거쳐서 구한다.

$$
D = V^{-1}AV  
$$

$$
VD = AV
$$

where $V = [v_{1}, v_{2}, ... , v_{n}]$ and $D = \begin{bmatrix}
{\lambda_1}& \cdots\\
\vdots & \ddots & \vdots \\
\cdots & \cdots&{\lambda_n}
\end{bmatrix}$

위의 식을 전개하면 아래와 같다.

$$
[Av_{1}, Av_{2}, \cdots Av_{n}] = [\lambda_1v_{1},\lambda_2v_{2}, \cdots, \lambda_{n}v_{n}] 
$$

$v_1$, $v_1$, $\cdots$, $v_{n}$ 은 eigen vector 이고 $\lambda_{1}$, $\lambda_{1}$, $\cdots$, $\lambda_{n}$ 는 eigen value이다.


만약 $V$가 invertable하다면, A는 다음과 같이 나타낼 수 있으며, 대각행렬 $D$는 존재한다.

참고: $V$가 invertable하다는 것은 V의 column vector끼리 linearly independent하다는 것이다.

$$
A = VDV^{-1}  
$$

In [1]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import eig
from numpy.linalg import inv

import time

In [3]:
# diagonalization and power of a matrix
A = np.array([[4, 0, -2], [2, 5, 4], [0, 0, 5]])
A

array([[ 4,  0, -2],
       [ 2,  5,  4],
       [ 0,  0,  5]])

In [6]:
eig_val, eig_vec = eig(A)
print(eig_val)
print(eig_vec)

[5. 4. 5.]
[[ 0.          0.4472136  -0.89442719]
 [ 1.         -0.89442719  0.        ]
 [ 0.          0.          0.4472136 ]]


In [7]:
D = np.diag(eig_val)
D

array([[5., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])

In [8]:
V = eig_vec
V

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

In [9]:
# A를 대각행렬로 나타내기
V.dot(D).dot(la.inv(V))

array([[ 4.,  0., -2.],
       [ 2.,  5.,  4.],
       [ 0.,  0.,  5.]])

In [10]:
la.matrix_power(A,5)

array([[ 1024,     0, -4202],
       [ 4202,  3125,  8404],
       [    0,     0,  3125]])

In [11]:
D_power_5 = np.diag(eig_val**5)
D_power_5

array([[3125.,    0.,    0.],
       [   0., 1024.,    0.],
       [   0.,    0., 3125.]])

In [12]:
V.dot(D_power_5).dot(la.inv(V))

array([[ 1024.,     0., -4202.],
       [ 4202.,  3125.,  8404.],
       [    0.,     0.,  3125.]])

In [13]:
# create a matrix A
A = np.array([[4., 4, 2, 3, -2], [0, 1, -2, -2, 2], [6, 12, 11, 2, -4], [9, 20, 10, 10, -6], [15, 28, 14, 5, -3]])

A = A + A.T
A = A/np.expand_dims(np.sum(A, 1), axis = 1)
print (A)

# initialize parameters
x = np.random.rand(5)
n_times = 1000000

# perform matrix multiplications
y = x
start_time = time.time()
for i in range(0, n_times):
    y = A.dot(y)
end_time = time.time()
elapse_time = end_time - start_time
print (y)
print (elapse_time)

[[ 0.17777778  0.08888889  0.17777778  0.26666667  0.28888889]
 [ 0.0625      0.03125     0.15625     0.28125     0.46875   ]
 [ 0.12903226  0.16129032  0.35483871  0.19354839  0.16129032]
 [ 0.19672131  0.29508197  0.19672131  0.32786885 -0.01639344]
 [ 0.2826087   0.65217391  0.2173913  -0.02173913 -0.13043478]]
[0.46569414 0.46569414 0.46569414 0.46569414 0.46569414]
0.8846371173858643


### 대각행렬을 사용했을 시, power 연산에서 효율적이다

In [14]:
eig_val, eig_vec = eig(A)
D = np.diag(eig_val)
V = eig_vec

# perform matrix multiplications using eigendecomposition
start_time = time.time()
y = V.dot((eig_val**n_times)*la.solve(V,x))
end_time = time.time()
elapse_time = end_time - start_time
print (y)
print (elapse_time)

[0.46569414 0.46569414 0.46569414 0.46569414 0.46569414]
0.0
